version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api-db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
